package com.chenfeng.symptom.domain.model.mybatis;

public class Syndrome {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_syndrome.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_syndrome.symptom_name
     *
     * @mbggenerated
     */
    private String symptomName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_syndrome.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_syndrome.syndrome_element_start
     *
     * @mbggenerated
     */
    private String syndromeElementStart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_syndrome.syndrome_element_end
     *
     * @mbggenerated
     */
    private String syndromeElementEnd;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_syndrome.id
     *
     * @return the value of t_syndrome.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_syndrome.id
     *
     * @param id the value for t_syndrome.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_syndrome.symptom_name
     *
     * @return the value of t_syndrome.symptom_name
     *
     * @mbggenerated
     */
    public String getSymptomName() {
        return symptomName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_syndrome.symptom_name
     *
     * @param symptomName the value for t_syndrome.symptom_name
     *
     * @mbggenerated
     */
    public void setSymptomName(String symptomName) {
        this.symptomName = symptomName == null ? null : symptomName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_syndrome.description
     *
     * @return the value of t_syndrome.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_syndrome.description
     *
     * @param description the value for t_syndrome.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_syndrome.syndrome_element_start
     *
     * @return the value of t_syndrome.syndrome_element_start
     *
     * @mbggenerated
     */
    public String getSyndromeElementStart() {
        return syndromeElementStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_syndrome.syndrome_element_start
     *
     * @param syndromeElementStart the value for t_syndrome.syndrome_element_start
     *
     * @mbggenerated
     */
    public void setSyndromeElementStart(String syndromeElementStart) {
        this.syndromeElementStart = syndromeElementStart == null ? null : syndromeElementStart.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_syndrome.syndrome_element_end
     *
     * @return the value of t_syndrome.syndrome_element_end
     *
     * @mbggenerated
     */
    public String getSyndromeElementEnd() {
        return syndromeElementEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_syndrome.syndrome_element_end
     *
     * @param syndromeElementEnd the value for t_syndrome.syndrome_element_end
     *
     * @mbggenerated
     */
    public void setSyndromeElementEnd(String syndromeElementEnd) {
        this.syndromeElementEnd = syndromeElementEnd == null ? null : syndromeElementEnd.trim();
    }
}