package com.chenfeng.symptom.domain.model.mybatis;

public class SyndromeElement {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_syndrome_element.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_syndrome_element.syndrome_element_start
     *
     * @mbggenerated
     */
    private String syndromeElementStart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_syndrome_element.syndrome_element_end
     *
     * @mbggenerated
     */
    private String syndromeElementEnd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_syndrome_element.is_relate
     *
     * @mbggenerated
     */
    private Integer isRelate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_syndrome_element.id
     *
     * @return the value of t_syndrome_element.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_syndrome_element.id
     *
     * @param id the value for t_syndrome_element.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_syndrome_element.syndrome_element_start
     *
     * @return the value of t_syndrome_element.syndrome_element_start
     *
     * @mbggenerated
     */
    public String getSyndromeElementStart() {
        return syndromeElementStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_syndrome_element.syndrome_element_start
     *
     * @param syndromeElementStart the value for t_syndrome_element.syndrome_element_start
     *
     * @mbggenerated
     */
    public void setSyndromeElementStart(String syndromeElementStart) {
        this.syndromeElementStart = syndromeElementStart == null ? null : syndromeElementStart.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_syndrome_element.syndrome_element_end
     *
     * @return the value of t_syndrome_element.syndrome_element_end
     *
     * @mbggenerated
     */
    public String getSyndromeElementEnd() {
        return syndromeElementEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_syndrome_element.syndrome_element_end
     *
     * @param syndromeElementEnd the value for t_syndrome_element.syndrome_element_end
     *
     * @mbggenerated
     */
    public void setSyndromeElementEnd(String syndromeElementEnd) {
        this.syndromeElementEnd = syndromeElementEnd == null ? null : syndromeElementEnd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_syndrome_element.is_relate
     *
     * @return the value of t_syndrome_element.is_relate
     *
     * @mbggenerated
     */
    public Integer getIsRelate() {
        return isRelate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_syndrome_element.is_relate
     *
     * @param isRelate the value for t_syndrome_element.is_relate
     *
     * @mbggenerated
     */
    public void setIsRelate(Integer isRelate) {
        this.isRelate = isRelate;
    }
}