package com.chenfeng.symptom.domain.repository.mybatis;

import com.chenfeng.symptom.domain.model.mybatis.Syndrome;

public interface SyndromeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_syndrome
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_syndrome
     *
     * @mbggenerated
     */
    int insert(Syndrome record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_syndrome
     *
     * @mbggenerated
     */
    int insertSelective(Syndrome record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_syndrome
     *
     * @mbggenerated
     */
    Syndrome selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_syndrome
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Syndrome record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_syndrome
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Syndrome record);
}